image: nberlette/gitpod-enhanced

tasks:
  - init: |
      export DENO_INSTALL="$HOME/.deno" PATH="$DENO_INSTALL/bin:$PATH"
      curl -fsSL https://deno.land/install.sh | sh -

vscode:
  extensions:
    - "denoland.vscode-deno"
    - "editorconfig.editorconfig"
    - "vsls-contrib.gistfs"
    - "sdras.night-owl"
    - "redhat.vscode-yaml"
    - "antfu.iconify"
    - "antfu.unocss"
    - "antfu.browse-lite"
    - "bierner.markdown-preview-github-styles"

github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: "gitpod-ready"
    addCheck: "prevent-merge-on-error"
